import { LearningModule, Quiz } from '@/types/education'

export const mockLearningModules: LearningModule[] = [
    {
        id: 'budgeting-basics',
        title: 'Budgeting Fundamentals',
        description: 'Learn the basics of creating and managing a budget',
        icon: 'Calculator',
        totalDuration: 45,
        completedLessons: 0,
        progress: 0,
        lessons: [
            {
                id: 'what-is-budgeting',
                title: 'What is Budgeting?',
                description: 'Understanding the fundamentals of budgeting',
                content: 'Placeholder content for budgeting basics...',
                duration: 10,
                difficulty: 'beginner',
                category: 'budgeting',
                completed: false,
                progress: 0,
            },
            {
                id: 'creating-your-first-budget',
                title: 'Creating Your First Budget',
                description: 'Step-by-step guide to creating a budget',
                content: 'Placeholder content for creating a budget...',
                duration: 15,
                difficulty: 'beginner',
                category: 'budgeting',
                completed: false,
                progress: 0,
            },
            {
                id: 'tracking-expenses',
                title: 'Tracking Your Expenses',
                description: 'Learn how to monitor and categorize expenses',
                content: 'Placeholder content for expense tracking...',
                duration: 12,
                difficulty: 'beginner',
                category: 'budgeting',
                completed: false,
                progress: 0,
            },
            {
                id: 'budget-adjustments',
                title: 'Making Budget Adjustments',
                description: 'How to modify your budget when life changes',
                content: 'Placeholder content for budget adjustments...',
                duration: 8,
                difficulty: 'intermediate',
                category: 'budgeting',
                completed: false,
                progress: 0,
            },
        ],
    },
    {
        id: 'investment-fundamentals',
        title: 'Investment Basics',
        description: 'Introduction to investing and building wealth',
        icon: 'TrendingUp',
        totalDuration: 60,
        completedLessons: 0,
        progress: 0,
        lessons: [
            {
                id: 'why-invest',
                title: 'Why Should You Invest?',
                description: 'Understanding the importance of investing',
                content: 'Placeholder content for investment importance...',
                duration: 12,
                difficulty: 'beginner',
                category: 'investing',
                completed: false,
                progress: 0,
            },
            {
                id: 'types-of-investments',
                title: 'Types of Investments',
                description: 'Stocks, bonds, ETFs, and more',
                content: 'Placeholder content for investment types...',
                duration: 18,
                difficulty: 'beginner',
                category: 'investing',
                completed: false,
                progress: 0,
            },
            {
                id: 'risk-and-return',
                title: 'Risk and Return',
                description: 'Understanding the relationship between risk and potential returns',
                content: 'Placeholder content for risk and return...',
                duration: 15,
                difficulty: 'intermediate',
                category: 'investing',
                completed: false,
                progress: 0,
            },
            {
                id: 'diversification',
                title: 'Diversification Strategies',
                description: 'How to spread risk across different investments',
                content: 'Placeholder content for diversification...',
                duration: 15,
                difficulty: 'intermediate',
                category: 'investing',
                completed: false,
                progress: 0,
            },
        ],
    },
    {
        id: 'saving-strategies',
        title: 'Saving Strategies',
        description: 'Build an emergency fund and save for goals',
        icon: 'PiggyBank',
        totalDuration: 35,
        completedLessons: 0,
        progress: 0,
        lessons: [
            {
                id: 'emergency-fund',
                title: 'Building an Emergency Fund',
                description: 'Why you need an emergency fund and how to build one',
                content: 'Placeholder content for emergency funds...',
                duration: 15,
                difficulty: 'beginner',
                category: 'saving',
                completed: false,
                progress: 0,
            },
            {
                id: 'saving-goals',
                title: 'Setting Saving Goals',
                description: 'How to set and achieve financial goals',
                content: 'Placeholder content for saving goals...',
                duration: 10,
                difficulty: 'beginner',
                category: 'saving',
                completed: false,
                progress: 0,
            },
            {
                id: 'high-yield-accounts',
                title: 'High-Yield Savings Accounts',
                description: 'Maximizing your savings with better interest rates',
                content: 'Placeholder content for high-yield accounts...',
                duration: 10,
                difficulty: 'intermediate',
                category: 'saving',
                completed: false,
                progress: 0,
            },
        ],
    },
    {
        id: 'retirement-planning',
        title: 'Retirement Planning',
        description: 'Plan for a secure financial future',
        icon: 'Target',
        totalDuration: 50,
        completedLessons: 0,
        progress: 0,
        lessons: [
            {
                id: 'retirement-basics',
                title: 'Retirement Planning Basics',
                description: 'Why start planning for retirement early',
                content: 'Placeholder content for retirement basics...',
                duration: 12,
                difficulty: 'beginner',
                category: 'retirement',
                completed: false,
                progress: 0,
            },
            {
                id: '401k-ira',
                title: '401(k) vs IRA',
                description: 'Understanding retirement account options',
                content: 'Placeholder content for retirement accounts...',
                duration: 18,
                difficulty: 'intermediate',
                category: 'retirement',
                completed: false,
                progress: 0,
            },
            {
                id: 'retirement-calculator',
                title: 'Using Retirement Calculators',
                description: 'Tools to plan your retirement savings',
                content: 'Placeholder content for retirement calculators...',
                duration: 20,
                difficulty: 'intermediate',
                category: 'retirement',
                completed: false,
                progress: 0,
            },
        ],
    },
]

export const mockQuizzes: Quiz[] = [
    {
        id: 'budgeting-quiz-1',
        lessonId: 'what-is-budgeting',
        passingScore: 80,
        completed: false,
        questions: [
            {
                id: 'q1',
                question: 'What is the primary purpose of a budget?',
                type: 'multiple-choice',
                options: ['To restrict spending completely', 'To track income and expenses', 'To impress financial advisors', 'To complicate your finances'],
                correctAnswer: 1,
                explanation: 'A budget helps you track where your money comes from and where it goes.',
            },
            {
                id: 'q2',
                question: 'The 50/30/20 rule suggests spending 50% on needs, 30% on wants, and 20% on savings.',
                type: 'true-false',
                correctAnswer: 1,
                explanation: 'This is a popular budgeting guideline that helps balance essential expenses, enjoyment, and future financial security.',
            },
        ],
    },
]
